paths:
  raw: ${hydra:runtime.cwd}/data/raw/
  assay: ./data/processed/assay/
  assay_id: ./data/processed/assay_id/
  feature: ./data/processed/feature/
  model: ./data/processed/model/
  prediction: ./data/processed/prediction/
  score: ./data/processed/score/

files:
  identifier: ${hydra:runtime.cwd}/data/external
  
params:
  dataset: meic  
  assay_size: 45
  support_set_size: 24
  feature: ecfp4_1024
  model: logistic
  test_prob: 0.05

hydra:
  sweep:
    subdir: ${hydra.job.override_dirname}
  sweeper:
    params:
      params.dataset: acute_oral_toxicity,nci60,toxcast,cancerrx,toxval,prism,meic
      params.feature: ecfp4_1024, chemberta
  job:
    chdir: True