paths:
  raw: ${hydra:runtime.cwd}/data/raw/
  assay: ./data/processed/assay/
  assay_id: ./data/processed/assay_id/
  feature: ./data/processed/feature/
  model: ./data/processed/model/
  prediction: ./data/processed/prediction/
  score: ./data/processed/score/

files:
  identifier: ${hydra:runtime.cwd}/data/external
  
params:
  dataset: nci60  
  assay_size: 128
  support_set_size: 32
  feature: ecfp4_1024
  model: xgboost
  test_prob: 0.05

xgboost:
  eta: 
    - 0.01
    - 0.1
  gamma:
    - 0.01
    - 0.05
    - 0.1
  max_depth:
    - 6
    - 9
    - 15
    - 24

hydra:
  sweep:
    subdir: ${hydra.job.override_dirname}
  sweeper:
    params:
      params.dataset: nci60, toxcast, meic, prism, toxval, cancerrx, acute_oral_toxicity
      params.feature: ecfp4_256
      params.model: logistic
  job:
    chdir: True